upstream user_svc {
    server user-service:8081;
}

upstream catalog_svc {
    server catalog-service:8082;
}

upstream order_svc {
    server order-service:8083;
}

server {
    listen 8080;

    location ~ ^/api/v1/(auth|users|notifications) {
        proxy_pass http://user_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/api/v1/services {
        proxy_pass http://catalog_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/api/v1/orders {
        proxy_pass http://order_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/(swagger|openapi\.yaml) {
        proxy_pass http://user_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
