components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 2
            thread_name: main-worker
        fs-task-processor:
            worker_threads: 1
            thread_name: fs-worker
    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8081
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard

        tracer:
            service-name: user-service

        statistics-storage: {}

        dynamic-config:
            fs-cache-path: ''
            fs-task-processor: fs-task-processor

        user-storage: {}

        jwt-auth-middleware: {}

        dns-client:
            fs-task-processor: fs-task-processor

        http-client:
            fs-task-processor: fs-task-processor

        default-server-middleware-pipeline-builder:
            append:
              - jwt-auth-middleware

        handler-auth-register:
            path: /api/v1/auth/register
            method: POST
            task_processor: main-task-processor

        handler-auth-login:
            path: /api/v1/auth/login
            method: POST
            task_processor: main-task-processor

        handler-users:
            path: /api/v1/users
            method: GET
            task_processor: main-task-processor

        handler-swagger-ui:
            path: /swagger
            method: GET
            task_processor: main-task-processor

        handler-openapi:
            path: /openapi.yaml
            method: GET
            task_processor: main-task-processor

        handler-email:
            path: /api/v1/notifications/email
            method: POST
            task_processor: main-task-processor
            api_key: "67ioz4iha8hm3zohe9udztzui5if5yjtct4phcge"
            sender_email: "noreply@profi.ru"
            sender_name: "Profi Service"
            list_id: "1"
