services:
  user-service:
    image: profi-services:latest
    build: .
    command: ["./build/user_service", "--config", "configs/user-service/static_config.yaml"]
    expose:
      - "8081"
    restart: unless-stopped

  catalog-service:
    image: profi-services:latest
    command: ["./build/catalog_service", "--config", "configs/catalog-service/static_config.yaml"]
    expose:
      - "8082"
    restart: unless-stopped

  order-service:
    image: profi-services:latest
    command: ["./build/order_service", "--config", "configs/order-service/static_config.yaml"]
    expose:
      - "8083"
    depends_on:
      - catalog-service
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - "./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - user-service
      - catalog-service
      - order-service
    restart: unless-stopped
